### ISSUE TITLE
Local / npx script produces different outputs

### ISSUE THREAD

**Issue by OllieJT** [renefournier/molly#5]
**Issue**
Running lilmolly via node_modules vs npx produced a different output. Local node_modules appears to be incorrectly identifying unused components.

This might onlt be an issue with pnpm, I haven't tested with yarn or npm yet.

**Details**
I have a somewhat large SvelteKit project. I installed molly with `pnpm add lilmolly -D`.

When running `lilmolly`, most of my components are marked as unused, though not all. (right of screenshot)

However, running `npx lilmolly` produces a more accurate output. (left of screenshot)

![](https://i.imgur.com/XtrzWOi.png)

**Comment by renefournier** [comment]
Hi Ollie,

Thanks for the note. I realized I neglected to publish some bug fixes/updates to npm since version `1.3.4`. I now have, and Molly is at `1.3.7`. https://www.npmjs.com/package/lilmolly When I try to reproduce your bug now, I don’t see a discrepancy. I was wondering, can you try again and let me know if the problem is gone or remains?

**Comment by OllieJT** [comment]
@renefournier 👍 yup, looks like this is resolved. Thank you!
